# Project
version=1.2.0+1.21.10
group=com.illusivesoulworks.polymorph
java_version=21

# Common
minecraft_version=1.21.10
mod_name=Polymorph
mod_author=Illusive Soulworks
mod_id=polymorph
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/polymorph/issues
sources_url=https://github.com/illusivesoulworks/polymorph
description=No more recipe conflicts! Adds an option to choose the crafting result if more than one is available.
minecraft_version_range=[1.21.10, 1.22)
minecraft_version_range_alt=~1.21.10

# Parchment
parchment_mc=1.21.10
parchment_version=2025.10.12

# Integrations
emi_version=1.1.22+1.21.1
jei_version=26.2.0.27
rei_version=21.9.812

# Fabric
fabric_version=0.138.3+1.21.10
fabric_loader_version=0.18.1
cca_version=7.2.0

# CurseForge Options
cf_id=388800
cf_page=https://www.curseforge.com/minecraft/mc-mods/polymorph
modrinth_id=tagwiZkJ
modrinth_page=https://modrinth.com/mod/polymorph
release_type=release
release_versions=1.21.10
changelog_link=https://github.com/illusivesoulworks/polymorph/blob/1.21.x/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/279/271/637277042531842540.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
